### ISSUE TITLE
504 errors for Ministry Client since Friday

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2095]
**Describe the bug**
A ministry client is asking if we changed Firewall settings last week because they are now getting 504 errors.

Search the CRM for "aest" for details on the systems.  There is also a post in #aws-how-to over in Rocket Chat.

**Additional context**
- The ministry is reporting this is affecting their production systems, medium/high severity 

**Definition of done**
- Help diagnose and fix the immediate problem for AEST
- Create tickets for more resilient approach changes that may need to happen afterwards

**Comment by prabhukiran9999** [comment]
Notes:
We believe(not 100% sure) this might be caused by an issue in the alibip lambda code. When someone deletes the alb or for some reason, the ALB DNS Name does not exist anymore the lambda fails at that point and the target groups do not get updated anymore and get in an unhealthy state. which results in 504's

**Comment by prabhukiran9999** [comment]
Notes:
We believe(not 100% sure) this might be caused by an issue in the alibip lambda code. When someone deletes the alb or for some reason, the ALB DNS Name does not exist anymore the lambda fails at that point and the target groups do not get updated anymore and get in an unhealthy state. which results in 504's

**Comment by ActionAnalytics** [comment]
Prabhu says we're 100% sure (we will break and repro in ECF Assembly)

**Comment by ActionAnalytics** [comment]
Closed as investigation is done.  Making other tickets
