### ISSUE TITLE
Standup Cloud Custodian 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#542]
**Describe the issue**
We are looking for ways to automate security checks. This is one of the 3 proposed solutions. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Cloud Custodian has been run on LZ1 and some output is available for comparison to other solutions.
- time-boxed to 2-3 days.

**Comment by wrnu** [comment]
# Cloud Custodian

## Summary

Cloud Custodian is a comprehensive tool for monitoring AWS security compliance and provides the ability to take action on findings.

### Pros

- Declarative policies (Compliance as Code).
- Multi-account support (c7n-org).
- Sends findings to Security Hub.
- Built in Lambda support.
  - Scheduled policies.
  - Events (e.g. AWS CloudTrail, Security Hub, Guard Duty) can trigger policy checks.
- Can take action on findings.
- CNCF Project

### Cons

- Large number of policies are required due to the declarative syntax and the way that regions are handled.
- No prior art to leverage for use in SEA.
- Infrastructure created by c7n is not truly declarative.
  - Lambdas deployed by policies are not automatically cleaned up when the policy is removed.
    - https://github.com/cloud-custodian/cloud-custodian/issues/48
  - There are clean up scripts available in the repo but this is a rough edge of the tool and engineering discussions are ongoing.
    - https://github.com/cloud-custodian/cloud-custodian/tree/master/tools/ops
  - Because of this it is may be best to maintain the infrastructure that runs c7n externally at this time and run c7n "in place". Further research is required.

## Notes

- Written in python.
- Policies are declarative and written in yaml.
- Supports AWS Security Hub Integration.
- Provides a tool `c7n-org` for running against multiple accounts.
 - Demo (https://github.com/wrnu/aws-sea-cloud-custodian)
