### ISSUE TITLE
Compliance review of US based AWS cost estimator

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#622]
**Describe the issue**
Because this is a tool we wish to make available for Ministry Program areas to use and Cloud Pathfinder as well.  Unfortunately, this tool is only available in the US, it's a non-specific region service.  We wish to look at any risk to using this, mostly to understand the process of using a non-Canadian service and to future proof.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- This is not intended to block Stuart's billing efforts, but to run in parallel in support of.

**Definition of done**
- Aim to have this as an entry on our list of compliant services
- May involve work on the PIA and STRA

**Comment by bluemel-gov** [comment]
- linked to #599

**Comment by hromanow** [comment]
Privacy portion done. Email sent to Ryan, cc'd Stu and Julian on outcome.

**Comment by bluemel-gov** [comment]
- Reviewing ticket/in progress as of March 2nd

**Comment by bluemel-gov** [comment]
@scayzer  FYI. 
- Since service is publicly accessible, Strongly recommend not putting any sensitive or compromising identifying information, such as customers' account numbers, function names, db names, etc into free-form fields such as a Name/description fields. This would also include AWS Pricing Calculator or other AWS services using the console, API, AWS CLI, or AWS SDKs and adding disclaimer to anytime we advise to use it. 
- No updates to PIA and STRA needed. just user awareness. 

Suggest clarifying that it's just https://calculator.aws/ not
https://calculator.s3.amazonaws.com/index.html
