### ISSUE TITLE
Book 2 days of 1:1 Refinement with each team member prior to Sprint Refinement

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#657]
**Describe the issue**
There's always a mad scramble before the demo to explain in clear language what we did. This is meant to frontload that work before the start of the sprint. 

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Refine current sprint tickets
- Tickets need to be understandable mainly for value based language suitable for inclusion in the demo.

**Comment by ActionAnalytics** [comment]
https://blog.zenhub.com/managing-your-product-backlog-with-ease/

"Running effective product backlog refinement meetings

While every software team operates effectively based on their own workflow, rhythm, size, and practiced project management philosophy, we share a few tips we've heard from teams on what works for their refinement sessions:

Have product backlog refinement meetings (typically 1-2 hours) on opposite weeks of sprint planning. This breaks up long meetings and gives product/stakeholders buffer time to answer questions about upcoming work before it gets accepted into a Sprint if something about a project is still unclear.

Have the entire development squad in attendance. Anyone who is going to be working on the project work or issues being discussed should attend. You should also have the Product owner / Design owner attend. Product and Design walkthrough the Issues in the product backlog and help answer questions as things get discussed.

Things to cover in the meeting: Spend the meeting reviewing upcoming pieces of work, breaking Issues down from large stories to development tasks, discussing if the top of the backlog is still prioritized effectively, as well as estimating new pieces of work.

End by reviewing if the placement of Issues in your backlog pipeline is still relevant. Keeping this pipeline prioritized helps teams understand the most important issue to work on next should everything in the Sprint be finished ahead of time."

We're going to do something similar where instead of moving the refinement team ceremony/meeting earlier, we will consider that refinement is an activity that can happen all sprint, and the activity of having the scrum master go over the tickets to check if they are well formed will happen the week before our scrum ceremony week.  As PO I'm balancing the advantages to having later refinements in the sprint which gives the team better information about the state of current work (one of the key inputs into creating new tickets) with the desire to push down refinement meeting length by doing the preparation work in advance so that tickets arrive in a more suitable state and especially so that tickets are written in a way that helps better serve as an input to demos.

**Comment by ActionAnalytics** [comment]
Will tackle next sprint, after Product Discovery and when PO dedicates more time to participate in Ticket creation activities
