### ISSUE TITLE
SPIKE: Research TF Cloud Blocking Runner scenario

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#768]
**Describe the issue**
TF Cloud in its current license mode only has one runner, and if a team accidentally gets it into a blocked state, it will block all teams.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Some solutions might be 
- different license models of TF Cloud
- a rocket chat alert on block state, flag the tech team to minimize downtime
- un-stuckify automation
- not allow remote execution - but don't get prepop of secrets (PO prefers to keep using)

**Definition of done**
- Tech team research to address
- Connect with PO about who to connect with
- Define tickets for addressing the problem
- timebox to 2

**Comment by sheaphillips** [comment]
We met with the team who reported this issue and came up with a "process" workaround that reduces the likelihood of getting blocked due to single runner.  Specifically, we talked about eparapet approaches for infrastructure-related elements and code deployment element within their pipeline/step.  This means that the former, which uses TFC,  happens relatively infreqnetly, and the latter which happens more often, can happen without TFC.

We also committed to rapid response in the event they di get blocked.

Going forward, we should evaluate/explore the single runner model with HashiCorp
