### ISSUE TITLE
Improvements to the xlsx format of the Filterable Billing Export

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#835]
**Describe the issue**
There is a excel plugin used to generate the billing exports.  We want to pre-format the spreadsheet in a common format for all the POs.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Column A deleted (the headerless system rownum)
- Row 2 deleted (empty spacer row)
- Columns fully expanded
- Freeze panes on project 2
- Filters on all headers turned on

**Comment by sheaphillips** [comment]
I believe there is also an intent to produce an Excel file *for each* billing group for the PO's in addition to aggregated including all billing groups ...this is not explicitly captured in to DoD but it is implied.  

Other requested features are implemented for the aggregated file ,but will continue work in order to generate a file per PO/billing group.

**Comment by sheaphillips** [comment]
XLS file per PO/billing group, as well as a file including *all* billing groups is now generated as part of the utility.
