### ISSUE TITLE
Intake SDPR to Funnel for their Azure request

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#955]
**Describe the issue**
There is an email thread about Azure access. Social Development and Poverty Reduction

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- See thread from Ryan F (copied in comment below)
- Ryan F is accepting of risk of rework if onboarding to Phase 2

**Definition of done**
- Jon to be invited to any meetings or onboarding
- Start them formally in the funnel
- Engage with Jon M and techs to look if possible to intake them under Phase 2 or if they would be better served for new onboarding process
- Get a sense of the priority and timeframe for SDPR

**Comment by scayzer** [comment]
This digital asset management system will contain all photos, videos, graphics, brochures etc. that are acceptable to share with the public.
Our primary uses of this system:
•	BC Parks staff province-wide will be able to share and collaborate using a consolidated repository of these files, which are currently spread and duplicated throughout various restricted LAN shares.
•	This will improve access to these sought-after resources and will remove file duplication.
•	We will be able to remove these files from our LAN shares, which will greatly reduce our storage costs.
•	Any government staff with an IDIR account will be able to search the BC Parks photo repository for photos and download/share what they need.  This will be particularly helpful for GCPE staff.
•	We’re in the midst of a development project, building an API-based content management system for BC Parks using Strapi.  This CMS is intended to be a central and consolidated source of data and content for BC Parks and is integrated with several other systems in government, including DataBC’s geographical warehouse.  This CMS will include API connectivity with ResourceSpace, which will feed park photos into the bcparks.ca site.
 
Through some fairly extensive research and various consultations (big thank you to Jeff for all your work on this!), we’ve determined that AWS VM hosting with OCIO is the optimal option.
In addition to the technical advantages of this option, this brings the opportunity for BC Parks and IIT to partner with OCIO to pilot AWS VM environments in government.  This will effectively set a technical precedent for further adoption of cloud VM hosting within BC Government through collaboration with OCIO, which will be a valuable benefit to all.
This solution will serve as a template for effective and efficient implementation of digital asset management systems throughout government.  This modernizing shift of cloud-hosted digital asset management equates to greater overall effectiveness of staff and ultimately our service to the public, while simultaneously reducing our currently vast storage costs.
We would like to begin with an inception meeting that will include all parties involved, followed up by a technical whiteboard session and design workshop, with further iterations of these if needed.
Further details on our assessment are below.  Does this all look and sound acceptable to you?  Please add anything I may have missed.
Thanks
Rob
 
Options considered:
•	On-Premises VM 
o	Relatively high cost: ~$1500-$1700/month
o	UNC mapping needed for storage will introduce instability
o	Server management and software updates are difficult due to permissions required
o	Public-facing access could be difficult due to strict firewall policies and complexity
•	OpenShift 
o	Not feasible, mainly due to: 
	storage requirements
	custom development needed to run ResourceSpace in a container environment
•	Azure VM 
o	GDX implementation is costing ~$350/month with 4TB of storage
o	Determined to be a valid option with OCIO, but implementation will take at least two months to accomplish, which will not work with the timeline of our project and contracted development team
•	AWS VM 
o	Cost is uncertain at the moment, but we’re guessing that it might be less than half the cost of the on-premises VM option (we previously priced AWS hosting at around $350/month)
o	Technically similar to the Azure VM option
o	Highest performing option
o	Active Directory integration is possible
o	We hope to start with a relatively low amount of allocated storage, such as ~150GB, and dynamically grow it as needed
o	Determined to be a valid option with OCIO and the implementation process can begin immediately
 
The responsibilities we have in mind are:
•  Compute: EC2 provisioning - BCP/OCIO 
•  Storage: EBS provisioning - BCP/OCIO 
•  Storage: S3 provisioning - BCP/OCIO 
•  Scaling sets (if needed) - BCP/OCIO 
•  Authentication - OCIO 
•  Network resources - OCIO 
•  ResourceSpace installation and updates - BCP 
•  Logging and monitoring - BCP/IIT/OCIO (we have ELK stack running in AWS already) 
•  Pipeline - BCP 
•  Metadata - IIT/BCP

**Comment by ActionAnalytics** [comment]
Jon says: Intake to prod may be difficult right now due to pre-phase 3 deployment items not yet in place

**Comment by ActionAnalytics** [comment]
Jon: If they want a space, they can try things out, but nothing is prod

**Comment by scayzer** [comment]
Exchanged emails with SDPR (Ryan F) and found out that they want some tricky permissions for their app:


Our application would require:
 
Application Permission: Sites.Selected (to enable our application to manage documents stored in a SharePoint site)
Application Permission: Users.Read.All (so our application can search through the government user list)
Application Permission: GroupMember.Read.All (not an absolute requirement, but it will allow us to leverage existing AD groups to manage certain application permissions, rather than re-creating groups in our app as we do for eApprovals with admin users)
 
These permissions require “Admin consent”. This means someone in our tenant with admin consent capabilities must sign off on these permissions before we can use them.

Jon and Jesse won't be able to provide these permissions, so have informed SDPR that they'll need to await set-up of our SEA and new processes in Azure - will keep in touch. Next check-in: late September
